### ISSUE TITLE
Not able to add multiple address to a single payid

### ISSUE THREAD

**Issue by RohitChangediya** [payid-org/payid#574]
Hi there,
I tried installing payid instance on a ubuntu server and created a payid using XRP address. How can i add BTC address to same payid ?

**Comment by hbergren** [comment]
Hi there,

So, using the private API (that runs on `8081` by default), you would `GET` the PayID you created:

```sh
curl --location --request GET 'http://127.0.0.1/users/alice$example.com' \
--header 'PayID-API-Version: 2020-05-28' \
--header 'Content-Type: application/json'
```

and then you could modify the user object you got as a response to include a BTC address, and `PUT` the new user object:

```sh
curl --location --request PUT 'http://127.0.0.1/users/alice$example.com' \
--header 'PayID-API-Version: 2020-05-28' \
--header 'Content-Type: application/json' \
--data-raw '{
    "payId": "<string>",
    "addresses": [
        {
            "paymentNetwork": "<string>",
            "environment": "<string>",
            "details": {
                "address": "<string>"
            }
        },
        {
            "payment_network": "<string>",
            "environment": "<string>",
            "details": {
                "address": "<string>"
            }
        }
    ]
}'
```

#### Misc

We have a proposal out for a [PATCH API](https://github.com/payid-org/payid/issues/142) that would allow you to actually update the user instead of needing to fetch and replace all of it. Feel free to upvote that issue if that seems useful.

Also, our [full API documentation](https://api.payid.org/?version=latest) might be helpful as well.

**Comment by hbergren** [comment]
Hey @RohitChangediya , were you able to add BTC to the same PayID?

**Comment by RohitChangediya** [comment]
Hey, yes. I was able to add multile addresses to same payid!

[Rohit Changediya - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=kpybv)	[kpybv]

On June 30, 2020 at 12:12 GMT, Hans Bergren <notifications@github.com> wrote:

Hey [@RohitChangediya](https://github.com/RohitChangediya) , were you able to add BTC to the same PayID?

**Comment by RohitChangediya** [comment]
Although the process is bit lengthy, but it worked :) I’d be looking forward for the patch!

[Rohit Changediya - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=kpycr)	[kpycr]

On June 30, 2020 at 12:13 GMT, Rohit Changediya <rohitchangediya@gmail.com> wrote:

Hey, yes. I was able to add multile addresses to same payid!

[Rohit Changediya - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=kpybv)	[kpybv]

On June 30, 2020 at 12:12 GMT, Hans Bergren <notifications@github.com> wrote:

Hey [@RohitChangediya](https://github.com/RohitChangediya) , were you able to add BTC to the same PayID?
